### ISSUE TITLE
Can't use comparison operators with the "unless" helper

### ISSUE THREAD

**Issue by gotts2swim** [bigcommerce/paper#117]
There seems to be a major bug where the unless helper does not allow the use of comparison operators. For Example, if I use this code:

```Handlebars
{{#each product.images}}
    {{#unless this.alt "===" "foo"}}
        <img src="{{getImage this 'productthumb_size' (cdn ../theme_settings.default_image_product)}}" alt="{{this.alt}}" title="{{this.alt}}">
    {{/unless}}
{{/each}}
```

The Stencil CLI will throw an error. Here's the stack trace I received:

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: options.fn is not a function
    at Object.<anonymous> (/Users/cory/.nvm/versions/node/v4.8.2/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/helpers/if.js:82:32)
    at Object.<anonymous> (/Users/cory/.nvm/versions/node/v4.8.2/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/base.js:210:35)
    at Object.template.39 (eval at <anonymous> (/Users/cory/.nvm/versions/node/v4.8.2/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:136:36), <anonymous>:117:33)
    at prog (/Users/cory/.nvm/versions/node/v4.8.2/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
    at execIteration (/Users/cory/.nvm/versions/node/v4.8.2/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/base.js:155:19)
    at Object.<anonymous> (/Users/cory/.nvm/versions/node/v4.8.2/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/base.js:164:11)
    at Object.template.main (eval at <anonymous> (/Users/cory/.nvm/versions/node/v4.8.2/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:136:36), <anonymous>:480:31)
    at ret (/Users/cory/.nvm/versions/node/v4.8.2/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at Object.invokePartial (/Users/cory/.nvm/versions/node/v4.8.2/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:218:12)
    at Object.invokePartialWrapper [as invokePartial] (/Users/cory/.nvm/versions/node/v4.8.2/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
```

**Comment by mcampa** [comment]
Is not a bug. `if` is the only helper where you can use comparison. 

Do this instead

```handlebars
{{#if this.alt "!==" "foo"}}
```

**Comment by gotts2swim** [comment]
Oh I didn't realize that was the case. I was confused because the documentation stated otherwise.

[https://stencil.bigcommerce.com/docs/handlebars-helpers-reference#section--unless-](https://stencil.bigcommerce.com/docs/handlebars-helpers-reference#section--unless-)

Statements can take these forms:
* An object, as in: `{{#unless object}}`.
* A comparison expression, as in: `{{#unless lvalue operator rvalue}}`.

**Comment by bc-mkatz** [comment]
That docs section (linked above) is now corrected. Thanks for catching this.
